### ISSUE TITLE
Help needed with Custom/Map states

### ISSUE THREAD

**Issue by sunalive** [phimath/stream_state#2]
I have a User Model like below:
`User({
    this.id,
    this.uid,
    this.name,
    this.imageUrl,
    this.email,
  });`

I wish to save all these as a collection object in my state variable (similar to arrays in session variables) and access them where needed.  Your documentation for Map and Custom are sparse and I just entered the flutter world so, finding it difficult to understand. :) Can you post an example as to how I create and access this object?

**Comment by phimath** [comment]
There are many ways to do this with StreamState.  It really will come down to how you want to organize your code. Lets say you have the following `User` class:
class User {
```
  int id;
  String uid;
  String name;
  String imageUrl;
  String email;

  User({this.id, this.uid, this.name, this.imageUrl, this.email});
}
```
If this is your only user, you can really just make a `StreamState` object with the type `User`:

```
var user = StreamState<User>(initial:User(
    id: 0,
    uid: 'username',
    name: 'Full Name',
    imageUrl: 'imageurl.com/image.png',
    email: 'user@gmail.com'
  ));
}
```
If you don't have a user ready to go when you create the `StreamState` object, you can also initialize to `null` and then set the user later:

```
var user = StreamState<User>(initial:null);
  
// and then later in your app:
  user.state = User(
    id: 0,
    uid: 'username',
    name: 'Full Name',
    imageUrl: 'imageurl.com/image.png',
    email: 'user@gmail.com'
  );
```

Note that currently, if you modify the user.state like this, you also need to call `user.forceUpdate()` to trigger your widgets to rebuild.  This is because it is a custom type.  I'm planning to change this behavior soon to be a bit cleaner.


If you have lots of users, you could store them in a list like this:

`var users = StreamState<List<User>>(initial:[]);`

and then you can just call `users.add(newUser)` followed by `users.forceUpdate()`.

There is also a full example of using a list of strings as state here: https://github.com/phimath/stream_state/blob/master/example/lib/list_state_main.dart

Does this help answer your question?

**Comment by phimath** [comment]
Oh and to access the object, you would just do:

`user.state.name` or `user.state.id`

The `state` attribute of the `StreamState` object _is_ the `User`.

And for the list example:

`users.state.first()` or `users.state[0] ` to access one of the users.

**Comment by sunalive** [comment]
Thanks. That worked! Love your plugin for its simplicity!
