### ISSUE TITLE
StreamState made of other StreamStates

### ISSUE THREAD

**Issue by jeffjose** [phimath/stream_state#3]
One pattern that is emerging as I spend more time is creating a _derived_ StreamState from other StreamStates.

Here's an example

```dart
class Store {
....
var user = StreamState<AppUser>(initial: null);
var blogposts = StreamState<List<Posts>>(initial: []);
}
final store = Store()
```

Lets assume this state is for an app similar to medium.com, and I want to know whether the "user is logged in" + "has created any blogposts".  I can combine 2 streams using `rxdart`, like so 

```dart
Stream hasUserCreatedAnyPosts = Rx.combineLatest2(store.user.stream, store.blogposts.stream, (u, bp) {
if (user != null && bp.length > 0) {
  return true
} else { 
return false
}
})
```

It'd be nice, if the above could be part of the `Store()` itself, by converting a stream like above into `StreamState`

Thoughts?

**Comment by phimath** [comment]
Sorry for the delay in getting back to you on this, finally had some time today to get to it.

I've not used `rxdart` before, but this is really cool.  I've implemented this as a named constructor `StreamState.combined()`.

I've updated the readme with how to use it, and also added an example file. 

Instead of limiting it to specifically 2 StreamStates, you can pass a list of as many as you want.  

Here is the bit from the readme:

## Derived / Combined State

You can derive a combined `StreamState` from other `StreamState` objects with the named constructor `StreamState.combined()`.

You can combine as many `StreamState` objects as you want.  The combiner will give you access to them as a list, but you can also use your `StreamState` objects directly.

Using StreamStates directly:

```dart
    counterA = StreamState<int>(initial: 0);
    counterB = StreamState<int>(initial: 0);
    totalCount = StreamState<int>.combined(
        [counterA, counterB],
        (_) => counterA.state + counterB.state,
    );
```

Using passed StreamStates:
```dart
    counterA = StreamState<int>(initial: 0);
    counterB = StreamState<int>(initial: 0);
    totalCount = StreamState<int>.combined(
        [counterA, counterB],
        (currentStates) => currentStates[0].state + currentStates[1].state,
    );
```

>Note that you can't directly persist a combined `StreamState` (but there shouldn't be a need to do this.)

Does this help?
